apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trailmagic
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: trailmagic
        name: trailmagic
    spec:
      containers:
      - image: us.gcr.io/horsecodes/trailmagic-web:fcfc6eaa7055564a41fb461b67cee9224d129fad
        name: trailmagic
        resources:
          requests:
            cpu: 0.25
          limits:
            memory: 512Mi
        ports:
        - containerPort: 80
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 45
